In [ ]:
import importlib
import quantum_function
importlib.reload(quantum_function)

from quantum_function import *

: 

In [2]:
Sz_1


Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 0.5  0.   0.   0. ]
 [ 0.   0.5  0.   0. ]
 [ 0.   0.  -0.5  0. ]
 [ 0.   0.   0.  -0.5]]

In [3]:
Sz_2

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 0.5  0.   0.   0. ]
 [ 0.  -0.5  0.   0. ]
 [ 0.   0.   0.5  0. ]
 [ 0.   0.   0.  -0.5]]

In [4]:
PlusPlus

Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.5]
 [0.5]
 [0.5]
 [0.5]]

In [5]:
gamma = 1   # Atomic decay rate

#Combination plus and minus of the two operators
c_ops =[np.sqrt(gamma) * ((Sz_1+Sz_2)/np.sqrt(2)), np.sqrt(gamma) * ((Sz_1-Sz_2)/np.sqrt(2))]


In [6]:
c_ops[0]

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 0.70710678  0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.         -0.70710678]]

In [7]:
c_ops[1]

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 0.          0.          0.          0.        ]
 [ 0.          0.70710678  0.          0.        ]
 [ 0.          0.         -0.70710678  0.        ]
 [ 0.          0.          0.          0.        ]]

### Calcoliamo l'azione dei due collapsing operators sullo stato $|++ \rangle$

In [8]:
Jump_plus = (c_ops[0]*PlusPlus).unit()
Jump_plus

Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[ 0.70710678]
 [ 0.        ]
 [ 0.        ]
 [-0.70710678]]

Otteniamo lo stato $\dfrac{|11\rangle - |00 \rangle}{\sqrt{2}}$ = $-|\phi_{-}\rangle$, stato di  antisimmetrico

In [9]:
Jump_minus = (c_ops[1]*PlusPlus).unit()
Jump_minus

Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[ 0.        ]
 [ 0.70710678]
 [-0.70710678]
 [ 0.        ]]

Otteniamo lo stato $\dfrac{|10\rangle - |01 \rangle}{\sqrt{2}}$ = $-|\psi_{-}\rangle$, stato di Bell antisimmetrico

### Vediamo cosa otteniamo col secondo Jump, partiamo dal caso di primo jump positivo, ossia da $-|\phi_{-}\rangle$

In [10]:
Jump_2_plus_plus = (c_ops[0]*Jump_plus).unit()
Jump_2_plus_plus

Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]

Ottengo $|\psi_{+}\rangle$

In [11]:
Jump_2_plus_minus = (c_ops[1]*Jump_plus)
Jump_2_plus_minus

Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]]

Qui lo stato nullo!

### Adesso dal primo jump negativo, ossia da $-|\psi_{-}\rangle$

In [12]:
Jump_2_minus_plus = (c_ops[0]*Jump_minus)
Jump_2_minus_plus

Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]]

Stato nullo anche qui

In [13]:
Jump_2_minus_minus = (c_ops[1]*Jump_minus).unit()
Jump_2_minus_minus

Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]

Analogamente si ottiene $|\psi_{+}\rangle$

In [14]:
# Function that acts as a collapsing operator on a given state

def jump_operator(c_ops, state):
    jump_plus = (c_ops[0]*state)
    
    if jump_plus.norm() != 0:
        jump_plus = jump_plus.unit()

    jump_minus = (c_ops[1]*state)

    if jump_minus.norm() != 0:
        jump_minus = jump_minus.unit()

    return jump_plus, jump_minus

### E così via, dopo il primo jump determino la parità del mio sottospazio e rimango lì, ogni jump alterna versione + e - dello stato di Bell associato alla parità. 
### Se pari ho gli stati $\phi$ se invece dispari gli stati $\psi$

In [15]:
Jump_3_plus_plus = jump_operator(c_ops, Jump_2_plus_plus)
Jump_3_plus_plus

(Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
 Qobj data =
 [[ 0.70710678]
  [ 0.        ]
  [ 0.        ]
  [-0.70710678]],
 Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
 Qobj data =
 [[0.]
  [0.]
  [0.]
  [0.]])

In [16]:
Jump_3_minus_minus = jump_operator(c_ops, Jump_2_minus_minus)
Jump_3_minus_minus

(Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
 Qobj data =
 [[0.]
  [0.]
  [0.]
  [0.]],
 Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
 Qobj data =
 [[ 0.        ]
  [ 0.70710678]
  [-0.70710678]
  [ 0.        ]])

In [20]:
#Nuove simulazioni

gamma = 1             # Atom decay rate
T_1 = 1 / gamma  # time constant for the decay

times = np.array(np.arange(0, 5*T_1, 0.01*T_1)) # time vector

my_name_states = ["++"]

my_initial_states = [PlusPlus]


#Creo dict di dataframe per ogni stato iniziale
photodetection_dfs = {}

ntraj = 100 # number of trajectories

# solve the master equation using montecarlo equation (photodetection) for every intial state
for name_state,state in zip(my_name_states, my_initial_states):
    my_photodetection = mcsolve(
        H_free, state, times,
        c_ops = [
        np.sqrt(gamma / 2) * (Sz_1+Sz_2),
        np.sqrt(gamma / 2) * (Sz_1-Sz_2)
        ],
        e_ops=[concurrence_for_solver_pure],
        ntraj=ntraj,
        options={"keep_runs_results":True, "map":"parallel"} #Necessary to create the keep the e_ops results for each trajectory
    )

    photodetection_dfs[f"{name_state}"] = pd.DataFrame(my_photodetection.expect[0].T, columns=[f"Traj_{i+1}" for i in range(ntraj)])
    photodetection_dfs[f"{name_state}"].index = np.arange(1, photodetection_dfs[f"{name_state}"].shape[0]+1)
    photodetection_dfs[f"{name_state}"].index.name = "Step"
    photodetection_dfs[f"{name_state}"]['mean'] = photodetection_dfs[f"{name_state}"].mean(axis=1)


10.0%. Run time:  11.59s. Est. time left: 00:00:01:44
20.0%. Run time:  11.67s. Est. time left: 00:00:00:46
30.0%. Run time:  11.74s. Est. time left: 00:00:00:27
40.0%. Run time:  11.82s. Est. time left: 00:00:00:17
50.0%. Run time:  11.88s. Est. time left: 00:00:00:11
60.0%. Run time:  11.94s. Est. time left: 00:00:00:07
70.0%. Run time:  12.01s. Est. time left: 00:00:00:05
80.0%. Run time:  12.06s. Est. time left: 00:00:00:03
90.0%. Run time:  12.12s. Est. time left: 00:00:00:01
100.0%. Run time:  12.17s. Est. time left: 00:00:00:00
Total run time:  13.25s
